name: photo_gallery
description: Photo gallery test app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  copy_with_extension: ^5.0.4
  dio: ^5.4.0
  envied: ^0.5.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_blurhash: ^0.8.2
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  gap: ^3.0.1
  hydrated_bloc: ^9.1.3
  intl: ^0.18.0
  intl_translation: ^0.18.2
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  path_provider: ^2.1.1
  retrofit: ^4.0.3
  shimmer: ^3.0.0
  stream_transform: ^2.1.0

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.4.6
  copy_with_extension_gen: ^5.0.4
  envied_generator: ^0.5.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^0.3.0
  retrofit_generator: '>=7.0.0 <8.0.0'
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
